# Generated by Django 5.2.6 on 2025-10-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="username",
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
